laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('nosso-historico', 'NossoHistoricoController@index')->name('nosso-historico');
    Route::get('faculdade', 'FaculdadeController@index')->name('faculdade');
    Route::get('escola-tecnica', 'EscolaController@index')->name('escola-tecnica');
    Route::get('ead', 'EadController@index')->name('ead');
    Route::get('fale-conosco', 'ContatoController@index')->name('fale-conosco');
    Route::post('fale-conosco', 'ContatoController@post')->name('fale-conosco.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('historico', 'HistoricoController', ['only' => ['index', 'update']]);
        Route::get('historico/{historico}/imagens/clear', [
            'as'   => 'painel.historico.imagens.clear',
            'uses' => 'HistoricoImagensController@clear'
        ]);
        Route::resource('historico.imagens', 'HistoricoImagensController', ['parameters' => ['imagens' => 'historico_imagens']]);
        Route::resource('faculdade', 'FaculdadeController', ['only' => ['index', 'update']]);
        Route::resource('faculdade.cursos', 'FaculdadeCursosController');
        Route::resource('escola', 'EscolaController', ['only' => ['index', 'update']]);
        Route::resource('escola.cursos', 'EscolaCursosController');
        Route::resource('ead', 'EadController', ['only' => ['index', 'update']]);
        Route::resource('ead.cursos', 'EadCursosController');
        Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Escola.php
<?php

namespace App\Models;

use App\Helpers\CropImage;
use Illuminate\Database\Eloquent\Model;

class Escola extends Model
{
    protected $table = 'escola';

    protected $guarded = ['id'];

    public function cursos()
    {
        return $this->hasMany('App\Models\EscolaCurso', 'escola_id');
    }

    public static function uploadImagem()
    {
        return CropImage::make('imagem', [
            'width'  => 600,
            'height' => null,
            'path'    => 'assets/img/escola/'
        ]);
    }
}

laravel/app/Http/Controllers/EscolaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Escola;
use App\Models\EscolaCurso;

class EscolaController extends Controller
{
    public function index()
    {
        $escola = Escola::first();

        $cursos = EscolaCurso::orderBy('titulo', 'ASC')->get();

        return view('frontend.escola-tecnica', compact('escola', 'cursos'));
    }
}

laravel/app/Http/Controllers/Painel/EscolaController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\EscolaRequest;
use App\Models\Escola;

class EscolaController extends Controller
{
    public function index()
    {
        $registro = Escola::first();

        return view('painel.escola.edit', compact('registro'));
    }

    public function update(EscolaRequest $request, Escola $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Escola::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.escola.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/escola/cursos/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Escola Técnica - Cursos /</small> Adicionar Curso</h2>
</legend>

{!! Form::open([
    'route' => ['painel.escola.cursos.store', $escola->id],
    'files' => true
]) !!}

@include('painel.escola.cursos.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/escola/cursos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Escola Técnica - Cursos /</small> Editar Curso</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.escola.cursos.update', $escola->id, $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.escola.cursos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/escola/cursos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('tipo', 'Tipo de Curso') !!}
    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título do Curso') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('link', 'Link do Curso') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.escola.cursos.index', $escola->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/escola/cursos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Escola Técnica - Cursos
        <a href="{{ route('painel.escola.cursos.create', $escola->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Curso</a>
    </h2>
</legend>


@if(!count($registros))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="escola_cursos">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Tipo de Curso</th>
            <th>Link do Curso</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($registros as $registro)
        <tr class="tr-row" id="{{ $registro->id }}">
            <td>{{ $registro->titulo }}</td>
            <td>{{ $registro->tipo }}</td>
            <td>{{ $registro->link }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.escola.cursos.destroy', $escola->id, $registro->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.escola.cursos.edit', [$escola->id, $registro->id] ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection