laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('nosso-historico', 'NossoHistoricoController@index')->name('nosso-historico');
    Route::get('faculdade', 'FaculdadeController@index')->name('faculdade');
    Route::get('escola-tecnica', 'EscolaController@index')->name('escola-tecnica');
    Route::get('ead', 'EadController@index')->name('ead');
    Route::get('fale-conosco', 'ContatoController@index')->name('fale-conosco');
    Route::post('fale-conosco', 'ContatoController@post')->name('fale-conosco.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('historico', 'HistoricoController', ['only' => ['index', 'update']]);
        Route::get('historico/{historico}/imagens/clear', [
            'as'   => 'painel.historico.imagens.clear',
            'uses' => 'HistoricoImagensController@clear'
        ]);
        Route::resource('historico.imagens', 'HistoricoImagensController', ['parameters' => ['imagens' => 'historico_imagens']]);
        Route::resource('faculdade', 'FaculdadeController', ['only' => ['index', 'update']]);
        Route::resource('faculdade.cursos', 'FaculdadeCursosController');
        Route::resource('escola', 'EscolaController', ['only' => ['index', 'update']]);
        Route::resource('escola.cursos', 'EscolaCursosController');
        Route::resource('ead', 'EadController', ['only' => ['index', 'update']]);
        Route::resource('ead.cursos', 'EadCursosController');
        Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Ead.php
<?php

namespace App\Models;

use App\Helpers\CropImage;
use Illuminate\Database\Eloquent\Model;

class Ead extends Model
{
    protected $table = 'ead';

    protected $guarded = ['id'];

    public function cursos()
    {
        return $this->hasMany('App\Models\EadCurso', 'ead_id');
    }

    public static function uploadImagem()
    {
        return CropImage::make('imagem', [
            'width'  => 600,
            'height' => null,
            'path'    => 'assets/img/ead/'
        ]);
    }
}

laravel/app/Http/Controllers/EadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ead;
use App\Models\EadCurso;

class EadController extends Controller
{
    public function index()
    {
        $ead = Ead::first();

        $cursos = EadCurso::orderBy('titulo', 'ASC')->get();
        // dd(count($cursos));

        return view('frontend.ead', compact('ead', 'cursos'));
    }
}

laravel/app/Http/Controllers/Painel/EadController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\EadRequest;
use App\Models\Ead;

class EadController extends Controller
{
    public function index()
    {
        $registro = Ead::first();

        return view('painel.ead.edit', compact('registro'));
    }

    public function update(EadRequest $request, Ead $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Ead::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.ead.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/ead/cursos/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>EAD - Cursos /</small> Adicionar Curso</h2>
</legend>

{!! Form::open([
    'route' => ['painel.ead.cursos.store', $ead->id],
    'files' => true
]) !!}

@include('painel.ead.cursos.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/ead/cursos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>EAD - Cursos /</small> Editar Curso</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.ead.cursos.update', $ead->id, $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.ead.cursos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/ead/cursos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('tipo', 'Tipo de Curso') !!}
    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título do Curso') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('link', 'Link do Curso') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.ead.cursos.index', $ead->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/ead/cursos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        EAD - Cursos
        <a href="{{ route('painel.ead.cursos.create', $ead->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Curso</a>
    </h2>
</legend>


@if(!count($registros))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="ead_cursos">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Tipo de Curso</th>
            <th>Link do Curso</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($registros as $registro)
        <tr class="tr-row" id="{{ $registro->id }}">
            <td>{{ $registro->titulo }}</td>
            <td>{{ $registro->tipo }}</td>
            <td>{{ $registro->link }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.ead.cursos.destroy', $ead->id, $registro->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.ead.cursos.edit', [$ead->id, $registro->id] ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection